server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    #    validationlar uchun
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/teacher
    username: postgres
    password: jshkm
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    open-in-view: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB #Maximum file size
      file-size-threshold: 2KB #Threshold of File Writing to Disk
      max-request-size: 215MB #Maximum request size
    ## Parameters required for file storage
    # All files uploaded through REST APIs will be stored in this directory
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: jabborovjaloliddin9@gmail.com
    password: vfkbtmpthytjfziq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

upload:
  dir: './uploads'

#swagger donfig
springdoc:
  swagger-ui:
    #    path: /swagger
    operations-sorter: method

security:
  key: "secretKeyaondfkasdnflkandsflk asdl as"

